CREATE TABLE [dbo].[FormComponentControls]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[LocalizationKey] nvarchar(255) NULL,
	[Name] nvarchar(255) NULL,
	[Description] nvarchar(255) NULL,	 
	[FormComponentDataTypeId] uniqueIdentifier NULL,	 
	[DisplayOrder] INT NULL,
	[Row] INT NULL,
	[ColumnWidth] INT NULL,
	[Position] INT NULL,
	[ExtraJson] nvarchar(1000) NULL,
	[ApiUrl] nvarchar(1000) NULL,
	[ViewModelColumnName] nvarchar(255) NULL,
	[DefaultOptions] nvarchar(Max) Null,
	[IsRequired] BIT NULL DEFAULT 0,
	[IsSystemRequired] BIT NULL DEFAULT 0,
	[IsMainItem] BIT NULL DEFAULT 0,
	[IsShowOnCreate] BIT NULL DEFAULT 0,
	[IsShowOnUpdate] BIT NULL DEFAULT 0,
	[IsDisabled] BIT NULL Default 0,
	[EnabledForAdmin] BIT NULL Default 0,	 
	[SectionId] UNIQUEIDENTIFIER NULL, 
	[IsDeleted]        BIT              NOT NULL DEFAULT 0,
	[UserCreatedById]  UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]        DATETIME2 (7)    NOT NULL,
    [UserModifiedById] UNIQUEIDENTIFIER NULL,
    [ModifiedOn]       DATETIME2 (7)    NULL,
	CONSTRAINT [FK_FormComponentDataTypeMap_TitanUser] FOREIGN KEY ([UserCreatedById]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_FormComponentDataTypeMap_TitanUser1] FOREIGN KEY ([UserModifiedById]) REFERENCES [dbo].[User] ([Id]),	 
	CONSTRAINT [FK_FormComponentDataTypeMap_FromComponentDataType] FOREIGN KEY ([FormComponentDataTypeId]) REFERENCES [dbo].[FormComponentDataType] ([Id]),	 
)
