CREATE TABLE [dbo].[User]
(   [Id]               UNIQUEIDENTIFIER NOT NULL,
    [FirstName]        NVARCHAR (64)    NULL,
    [LastName]         NVARCHAR (64)    NULL,
	[UserName]		   NVARCHAR (50)    NOT NULL UNIQUE,
    [DisplayName]      NVARCHAR (128)   NULL,
    [EmailAddress]     NVARCHAR (128)   NULL,
	[PhoneNumber]      NVARCHAR (64)    NULL,
    [IsEverLoggedIn]   BIT              NULL,
    [LastLoggedOn]     DATETIME2 (7)    NULL,
    [DefaultLocale]    NVARCHAR (10)    NOT NULL DEFAULT 'en-us',
	[SyncFromAD]       BIT NULL DEFAULT 1,
    [IsDeleted]        BIT              NOT NULL DEFAULT 0,
    [DepartmentId]     UNIQUEIDENTIFIER NULL,
	[RoleId]     UNIQUEIDENTIFIER NULL,
	[DefaultTenantId]  UNIQUEIDENTIFIER NULL,
	[DefaultTimeZoneId] NVARCHAR(100)   NULL DEFAULT 'Pacific Standard Time',
    [CreatedOn]        DATETIME2 (7)    NULL,
    [UserCreatedById]  UNIQUEIDENTIFIER NULL,
    [ModifiedOn]       DATETIME2 (7)    NULL,
    [UserModifiedById] UNIQUEIDENTIFIER NULL,
    [UserDeletedById]  UNIQUEIDENTIFIER NULL,
    [DeletedOn]        DATETIME2 (7)    NULL,
	[LicenseTypeId]		uniqueidentifier NULL,
	[PassWord]     NVARCHAR (500)   NULL DEFAULT '',
	[ActiveDirectoryGroupId] uniqueidentifier NULL
    CONSTRAINT [PK_TitanUser] PRIMARY KEY CLUSTERED ([Id] ASC),
    [isServiceUser] BIT NOT NULL DEFAULT 0, 
    [License] UNIQUEIDENTIFIER NULL, 
    [ServiceId] UNIQUEIDENTIFIER NULL, 
    [AccessTokenLifeTimeInDays] SMALLINT NOT NULL DEFAULT 0, 
	[EmployeeTypeId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [FK_TitanUser_Tenant] FOREIGN KEY ([DefaultTenantId]) REFERENCES [Tenant]([Id])
);
